---
- name: "Update apt packages"
  become: true
  apt:
    update_cache: yes

- name: "Upgrade apt packages"
  become: true
  apt:
    upgrade: yes

- name: "Install dependencies"
  shell: |
    cd ~/
    ls
    sudo apt-get update -y

- name: "Install pm2"
  become: true
  npm:
    name: "pm2"
    global: yes
    production: yes
    state: "present"
