---
# - name: "Update apt packages"
#   become: true
#   apt:
#     update_cache: yes

# - name: "Upgrade apt packages"
#   become: true
#   apt:
#     upgrade: yes

# - name: "Install dependencies"
#   shell: |
#     cd ~/
#     echo "test"
#     sudo apt-get update -y
#     yes Y | sudo apt install apt-transport-https ca-certificates curl software-properties-common
