---
# - name: Clone GIT AmeDin Capstone
#   become: yes
#   shell: |
#     git clone https://github.com/AmeDin/capstone.git

- name: Start minikube
  become: yes
  shell: |
    minikube start
    # minikube delete --all --purge
    # sudo apt-get install -y conntrack
    # minikube start --network-plugin=cni --cni=calico

- name: Create blue pod
  become: yes
  shell: |
    kubectl run blue --image=nginxdemos/hello --port=80 --labels app=blue
    while [[ $(kubectl get pods blue -o 'jsonpath={..status.conditions[?(@.type=="Ready")].status}') != "True" ]]; do echo "waiting for pod" && sleep 1; done

- name: Run port-forward blue pod
  become: yes
  shell: |
    nohup kubectl port-forward --address 0.0.0.0 blue 30000:80

# - name: Apply blue deployment
#   become: yes
#   shell: |
#     # cd capstone/k8s/
#     # kubectl apply -f blue.yml
#     # nohup kubectl port-forward --address 0.0.0.0 service/blue 30000:8081
#     kubectl run blue --image=nginxdemos/hello --port=80 --labels app=blue
#     nohup kubectl port-forward --address 0.0.0.0 blue 30000:80
