# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: bluepod
# spec:
#   replicas: 2
#   selector:
#     matchLabels:
#       app: bluepod
#   template:
#     metadata:
#       labels:
#         app: bluepod
#     spec:
#       containers:
#         - image: nginxdemos/hello # The image used is nginxdemos/hello.
#           name: bluepod
#           ports:
#             - containerPort: 8080
#               protocol: TCP

# ---
apiVersion: v1
kind: Service
metadata:
  name: blue
spec:
  selector:
    app: blue
  type: NodePort
  ports:
    - protocol: TCP
      targetPort: 80
      port: 8081
      nodePort: 30000
