apiVersion: apps/v1
kind: Deployment
metadata:
  name: green
spec:
  replicas: 1
  selector:
    matchLabels:
      app: green
  template:
    metadata:
      labels:
        app: green
    spec:
      containers:
        - image: nginxdemos/hello # The image used is nginxdemos/hello.
          name: container-0
          ports:
            - name: http-server
              containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: blue
  labels:
    app: bluegreenlb
spec:
  selector:
    app: blue
  ports:
    - name: blueservice
      targetPort: 80
      port: 8080
      protocol: TCP
  type: NodePort
