apiVersion: apps/v1
kind: Deployment
metadata:
  name: green
spec:
  replicas: 1
  selector:
    matchLabels:
      app: green
  template:
    metadata:
      labels:
        app: green
    spec:
      containers:
        - image: amedin/green:v1.0.0 # The image used is nginxdemos/hello.
          name: green
          ports:
            - name: http-server
              containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: green
spec:
  selector:
    app: green
  type: NodePort
  ports:
    - protocol: TCP
      targetPort: 80
      port: 8080
