---
# - name: Clone GIT AmeDin Capstone
#   become: yes
#   shell: |
#     git clone https://github.com/AmeDin/capstone.git

- name: Create green pod
  become: yes
  shell: |
    kubectl run green --image=amedin/green:v2.0.0 --port=80 --labels app=green

- name: Wait for kubectl pods to be read
  wait_for:
    timeout: 15

- name: Swtich Blue port-forward to Green pod
  become: yes
  shell: |
    if kubectl get pods blue | grep running 
    then
        if lsof -i :30000 | grep kubectl 
        then
            echo "blue is port forwarding"
            kill $(lsof -t -i:30000)
            nohup kubectl port-forward --address 0.0.0.0 green 30000:80 > nohup.out 2>&1 &
        else
            echo "none"
        fi
    else
        echo "no blue pods running"
    fi

# - name: Apply blue deployment
#   become: yes
#   shell: |
#     # cd capstone/k8s/
#     # kubectl apply -f blue.yml
#     # nohup kubectl port-forward --address 0.0.0.0 service/blue 30000:8081
#     kubectl run blue --image=nginxdemos/hello --port=80 --labels app=blue
#     nohup kubectl port-forward --address 0.0.0.0 blue 30000:80
