---
- name: install kubectl repository
  apt_repository:
    repo: deb https://dl.k8s.io/release/v1.27.1/bin/linux/amd64/kubectl
    state: present
  become: true
- name: Installing kubectl
  apt:
    name: kubectl
    state: present
- name: Installing Docker
  apt:
    name: docker
    state: present
- name: Installing conntrack
  apt:
    name: conntrack
    state: present
- name: Downloading minikube
  get_url:
    url: https://storage.googleapis.com/minikube/releases/latest/minikube-latest.x86_64.rpm
    dest: /root/minikube-latest.x86_64.rpm
- name: Installing minkube
  apt:
    name: /root/minikube-latest.x86_64.rpm
    state: present
- name: Starting Minikube driver using none
  become: yes
  shell: |
    minkube start --driver=none
