---
- name: install kubectl repository
  uri:
    url: https://dl.k8s.io/release/stable.txt
    return_content: yes
  register: version
- name: Download the latest kubectl release
  uri:
    url: https://dl.k8s.io/release/{{ version.content }}/bin/linux/amd64/kubectl
    dest: /home/{{ ansible_user }}
  register: kubectl
- name: Check if kubectl is installed
  shell: kubectl version --client
  register: client
  failed_when: client.rc > 1
- name: Install aptitude
  apt:
    name: aptitude
    state: latest
    update_cache: true
- name: Install required system packages
  apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    state: latest
    update_cache: true

- name: Install Docker Repository
  become: yes
  shell: |
    sudo rm -r /usr/share/keyrings/docker-archive-keyring.gpg
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
    sudo apt update
    apt-cache policy docker-ce
    sudo apt install docker-ce -y

- name: Starting Docker
  become: yes
  shell: |
    sudo systemctl status docker

- name: Installing conntrack
  apt:
    name: conntrack
    state: present

# - name: Installing minkube
#   uri:
#     url: https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
#     dest: /home/{{ ansible_user }}
#   register: minikubelinuxamd64
- name: Installing minkube
  become: yes
  shell: |
    curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
    sudo install minikube-linux-amd64 /usr/local/bin/minikube

- name: Cleaning up Minikube driver using none
  become: yes
  shell: |
    echo -e "ubuntu" | su - ubuntu
    sudo usermod -aG docker ubuntu && newgrp docker
    minikube start --driver=docker --force
