---
- name: import the kubectl apt key
  apt_key:
    url: https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
    state: present
  become: true
- name: install kubectl repository
  apt_repository:
    repo: deb https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64 stable main
    state: present
  become: true
- name: Installing kubectl
  apt:
    name: kubectl
    state: present
- name: Installing Docker
  apt:
    name: docker
    state: present
- name: Installing conntrack
  apt:
    name: conntrack
    state: present
- name: Downloading minikube
  get_url:
    url: https://storage.googleapis.com/minikube/releases/latest/minikube-latest.x86_64.rpm
    dest: /root/minikube-latest.x86_64.rpm
- name: Installing minkube
  apt:
    name: /root/minikube-latest.x86_64.rpm
    state: present
- name: Starting Minikube driver using none
  become: yes
  shell: |
    minkube start --driver=none
